services:
  postgres-users:
    image: postgres:18.0-alpine3.22
    container_name: postgres-users
    ports:
      - 5400:5432
    environment:
      POSTGRES_USER: ${USERS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USERS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USERS_POSTGRES_DB}
    volumes:
      - postgres-data-users:/var/lib/postgresql

  postgres-orders:
    image: postgres:18.0-alpine3.22
    container_name: postgres-orders
    ports:
      - 5401:5432
    environment:
      POSTGRES_USER: ${ORDERS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ORDERS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ORDERS_POSTGRES_DB}
    volumes:
      - postgres-data-orders:/var/lib/postgresql

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    env_file:
      - apps/api-gateway/.env
    ports:
      - 3000:3000

  users-service:
    build:
      context: .
      dockerfile: apps/users/Dockerfile
    container_name: users-service
    env_file:
      - apps/users/.env
    ports:
      - 3001:3001
    depends_on:
      - api-gateway
      - postgres-users

  orders-service:
    build:
      context: .
      dockerfile: apps/orders/Dockerfile
    container_name: orders-service
    env_file:
      - apps/orders/.env
    ports:
      - 3002:3002
    depends_on:
      - api-gateway
      - postgres-orders

volumes:
  postgres-data-users:
  postgres-data-orders:
